//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kids__Personal_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kids__Personal_Account()
        {
            this.Visit_Tabel = new HashSet<Visit_Tabel>();
        }
    
        public int ID_Personal_Account { get; set; }
        public int Kid_Garden_Number { get; set; }
        public int Parent_Tabel_Number { get; set; }
        public string Kid_FIO { get; set; }
        public double Pay_Sum { get; set; }
        public Nullable<bool> Paid { get; set; }
    
        public virtual Kid_Garden Kid_Garden { get; set; }
        public virtual Parent Parent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit_Tabel> Visit_Tabel { get; set; }
    }
}
